# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
  paths:
    include:
    - '*'
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - main
    - release/*
  paths:
    include:
    - '*'
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

variables:
  - name: _TeamName
    value: dotnet-core

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/pipelines/templates/build-job.yml
    parameters:
      osGroup: Windows
      archType: x64
      runTests: false
      ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        isOfficialBuild: true
        pool:
          name: NetCore1ESPool-Internal
          demands: ImageOverride -equals '1es-windows-2019'
      ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
        pool:
          vmImage: '1es-windows-2019'

  - template: /eng/pipelines/templates/build-job.yml
    parameters:
      osGroup: Linux
      archType: x64
      runTests: false
      container: 
        registry: mcr
        image: ubuntu-18.04
      ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        isOfficialBuild: true
        pool:
          name: NetCore1ESPool-Internal
          demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
      ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
        pool:
          vmImage: 'ubuntu-18.04'

  - template: /eng/pipelines/templates/build-job.yml
    parameters:
      osGroup: Linux
      archType: arm64
      runTests: false
      ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
        pool:
          name: NetCore-Public
          demands: ImageOverride -equals 1es-ubuntu-2004-open
      ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        isOfficialBuild: true
        pool:
          name: NetCore1ESPool-Internal
          demands: ImageOverride -equals build.ubuntu.1804.amd64
      container:
        registry: mcr.microsoft.com/dotnet-buildtools/prereqs
        image: ubuntu-18.04-cross-arm64

  - template: /eng/pipelines/templates/build-job.yml
    parameters:
      osGroup: Linux
      archType: arm
      runTests: false
      ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
        pool:
          name: NetCore-Public
          demands: ImageOverride -equals 1es-ubuntu-2004-open
      ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        isOfficialBuild: true
        pool:
          name: NetCore1ESPool-Internal
          demands: ImageOverride -equals build.ubuntu.1804.amd64
      container:
        registry: mcr.microsoft.com/dotnet-buildtools/prereqs
        image: ubuntu-18.04-cross-arm

  - template: /eng/pipelines/templates/build-job.yml
    parameters:
      osGroup: macOS
      archType: x64
      runTests: false
      pool:
        vmImage: 'macOS-10.15'

# Publish and validation steps. Only run in official builds
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: \eng\common\templates\post-build\post-build.yml
    parameters:
      publishingInfraVersion: 3
      validateDependsOn:
        - build
      enableSourceLinkValidation: true
